"""Configuration: models, loading, validation."""

from .loader import CONFIG_ENV, ConfigError, LoadedConfig, config_path_from_env, load_config
from .models import (
    AppConfig,
    AutoRead,
    BridgeEntry,
    BridgeSource,
    MaxConfig,
    MediaConfig,
    OutgoingTyping,
    OwnMessagesConfig,
    OwnPresence,
    PathsConfig,
    PresenceConfig,
    ProvisioningConfig,
    ProvisioningMode,
    ReactionsConfig,
    ReactionStyle,
    ReadReceiptStyle,
    ResolvedBridge,
    TelegramConfig,
    TimestampStyle,
    UnknownChatPolicy,
)

__all__ = [
    "CONFIG_ENV",
    "AppConfig",
    "AutoRead",
    "BridgeEntry",
    "BridgeSource",
    "ConfigError",
    "LoadedConfig",
    "MaxConfig",
    "MediaConfig",
    "OutgoingTyping",
    "OwnMessagesConfig",
    "OwnPresence",
    "PathsConfig",
    "PresenceConfig",
    "ProvisioningConfig",
    "ProvisioningMode",
    "ReactionStyle",
    "ReactionsConfig",
    "ReadReceiptStyle",
    "ResolvedBridge",
    "TelegramConfig",
    "TimestampStyle",
    "UnknownChatPolicy",
    "config_path_from_env",
    "load_config",
]
