"""Temporary files: created by us, named by us, always removed.

Media passes through disk because neither side streams: MAX hands out an HTTPS
URL, Telegram wants a file object, and the bridge is the only thing in between.
Every byte that lands on disk goes through this module so that three properties
hold everywhere.

* The path is generated by `mkstemp` inside `temp_dir` — a name from a message
  never becomes a path (`names.sanitize_filename` is for display only).
* The file is removed in a `finally`, including when delivery raised.
* Anything a crash left behind is swept on the next start, so a bridge that
  died mid-download does not slowly fill the disk.
"""

from __future__ import annotations

import logging
import os
import stat
import tempfile
import time
from collections.abc import Iterator
from contextlib import contextmanager
from dataclasses import dataclass
from pathlib import Path

logger = logging.getLogger(__name__)

#: Prefix for everything we create, so the sweeper can recognise its own litter.
PREFIX = "telemax-"

#: How long an orphan may survive before the sweeper takes it. Longer than any
#: single transfer, short enough that a crash does not cost a day of disk.
ORPHAN_TTL_SECONDS = 6 * 3600


class MediaTooLargeError(Exception):
    """The file is bigger than `media.max_file_size_mb` allows."""

    def __init__(self, limit_bytes: int, actual_bytes: int | None = None) -> None:
        self.limit_bytes = limit_bytes
        self.actual_bytes = actual_bytes
        limit_mb = limit_bytes / 1024 / 1024
        if actual_bytes is None:
            super().__init__(f"file is larger than the {limit_mb:.0f} MB limit")
        else:
            super().__init__(
                f"file is {actual_bytes / 1024 / 1024:.1f} MB, over the {limit_mb:.0f} MB limit"
            )


@dataclass(frozen=True, slots=True)
class LocalFile:
    """A downloaded file, ready to be handed to the other side."""

    path: Path
    #: The name the owner sees. Sanitised, and never used to build `path`.
    display_name: str
    size: int
    content_type: str | None = None


class TempFiles:
    def __init__(self, temp_dir: Path) -> None:
        self._dir = temp_dir

    def ensure_dir(self) -> None:
        self._dir.mkdir(parents=True, exist_ok=True)
        os.chmod(self._dir, stat.S_IRWXU)  # 0700: media is private correspondence

    @contextmanager
    def reserve(self, suffix: str = "") -> Iterator[Path]:
        """A private empty file that is gone by the time the block exits.

        The suffix is only a hint for tools that sniff extensions; it is
        sanitised because it may come from a remote file name.
        """
        self.ensure_dir()
        safe_suffix = "".join(ch for ch in suffix if ch.isalnum() or ch == ".")[:16]
        handle, raw_path = tempfile.mkstemp(prefix=PREFIX, suffix=safe_suffix, dir=self._dir)
        os.close(handle)
        path = Path(raw_path)
        os.chmod(path, stat.S_IRUSR | stat.S_IWUSR)  # 0600
        try:
            yield path
        finally:
            path.unlink(missing_ok=True)

    def sweep(self, *, ttl_seconds: float = ORPHAN_TTL_SECONDS) -> int:
        """Remove leftovers from previous runs. Returns how many went."""
        if not self._dir.exists():
            return 0

        deadline = time.time() - ttl_seconds
        removed = 0
        for path in self._dir.glob(f"{PREFIX}*"):
            try:
                if path.is_file() and path.stat().st_mtime < deadline:
                    path.unlink(missing_ok=True)
                    removed += 1
            except OSError:
                # A file that vanished under us, or one we may not touch: the
                # sweeper is housekeeping and must never break a start-up.
                logger.debug("could not sweep %s", path.name, exc_info=True)
        if removed:
            logger.info("swept %s orphaned media file(s)", removed)
        return removed
