"""`TelegramMediaSender` over aiogram: one Bot API method per attachment kind.

Nothing here decides *which* method a MAX attachment deserves — that choice is
made in `media.delivery`. This module knows how to hand aiogram a file, how to
read a message id back, and — the part that had to be rewritten — when it is
allowed to offer the same content to Telegram a second time.

**Every fallback in this file is a message-creating call.** They used to be
guarded by `except Exception`, which reads a timeout exactly the same way it
reads a refusal. A timeout after Telegram had already accepted the content
therefore produced a second message: a photo *and* a document, a sticker *and* a
photo, and — the worst of them — an album *and* the same three photos again, one
at a time. Six messages for three attachments, inside a single attempt, with no
retry involved at all.

So there is exactly one rule here now, and `bridge.telegram.errors` is the only
place that applies it: **a second creating call requires the server to have
answered**, and to have answered about the *form* of the content. Silence of any
kind — timeout, reset, 5xx, cancellation — travels up untouched, and the queue's
settlement policy turns it into a question for the owner.
"""

from __future__ import annotations

import logging
from typing import Any

from aiogram.exceptions import TelegramBadRequest
from aiogram.types import (
    BufferedInputFile,
    FSInputFile,
    InlineKeyboardButton,
    InlineKeyboardMarkup,
    InputMediaPhoto,
    InputMediaVideo,
    MessageEntity,
)

from bridge.max_client import AttachmentKind
from bridge.media.delivery import AlbumReceipt, OutgoingMedia, check_album_receipt
from bridge.routing.delivery import UnconfirmedDeliveryError
from bridge.telegram import (
    BotRegistry,
    TelegramTransportUnavailableError,
    refused_group,
    refused_representation,
)

logger = logging.getLogger(__name__)


def _url_keyboard(buttons: list[tuple[str, str]] | None) -> InlineKeyboardMarkup | None:
    """URL buttons as an inline keyboard, one per row, or None for none."""
    if not buttons:
        return None
    return InlineKeyboardMarkup(
        inline_keyboard=[[InlineKeyboardButton(text=text, url=url)] for text, url in buttons]
    )


class RegistryMediaSender:
    def __init__(self, registry: BotRegistry) -> None:
        self._registry = registry

    def _bot(self, bot_id: int) -> Any:
        """The live bot, or a proven "nothing was sent".

        It used to answer `None`, which the delivery turned into "Telegram
        returned no message id" — the wording for an *unconfirmed* send. A bot
        that is no longer registered is the opposite of unconfirmed: no request
        was built, let alone made.
        """
        live = self._registry.by_bot_id(bot_id)
        if live is None:
            raise TelegramTransportUnavailableError(f"bot {bot_id} is no longer registered")
        return live.bot

    @staticmethod
    def _file(media: OutgoingMedia) -> FSInputFile:
        # The name is the sanitised display name; the path was generated by us.
        return FSInputFile(media.path, filename=media.file_name)

    @staticmethod
    def _cover(media: OutgoingMedia) -> BufferedInputFile | None:
        """The upright cover, when the delivery drew one.

        Without it Telegram makes its own out of the stored frame, and a phone
        video carries a rotation the stored frame does not — which is how a clip
        that plays upright ends up with a cover lying on its side.
        """
        if not media.thumbnail:
            return None
        return BufferedInputFile(media.thumbnail, filename="cover.jpg")

    @staticmethod
    def _entities(items: list[dict[str, Any]] | None) -> list[MessageEntity] | None:
        """Formatting ranges travel as plain dicts until aiogram needs them."""
        if not items:
            return None
        return [MessageEntity.model_validate(item) for item in items]

    @staticmethod
    def _id(sent: Any) -> int:
        """The id Telegram named, or an admission that it named none.

        `ok: true` with nothing to identify the message by is the one answer that
        proves a message exists and leaves us unable to point at it. It is not a
        failure to retry and not a success to record — it is the definition of
        unconfirmed, and a second send in any form would duplicate it.
        """
        message_id = getattr(sent, "message_id", None)
        if message_id is None:
            raise UnconfirmedDeliveryError("Telegram accepted the message and named no id")
        value = int(message_id)
        if value <= 0:
            raise UnconfirmedDeliveryError(f"Telegram named an impossible message id {value}")
        return value

    def _degrade(self, media: OutgoingMedia, error: TelegramBadRequest, *, to: str) -> None:
        """Log the one permitted fallback, in structure only."""
        logger.info(
            "Telegram refused %s as %s (%s); sending it as %s",
            media.file_name,
            media.kind.value,
            error,
            to,
        )

    async def send_photo(
        self, bot_id: int, chat_id: int, media: OutgoingMedia, *, reply_to: int | None
    ) -> int:
        bot = self._bot(bot_id)
        try:
            sent = await bot.send_photo(
                chat_id=chat_id,
                photo=self._file(media),
                caption=media.caption,
                caption_entities=self._entities(media.caption_entities),
                reply_to_message_id=reply_to,
            )
        except TelegramBadRequest as error:
            # Telegram refuses photos with odd dimensions or an extension it does
            # not recognise. It answered, so nothing was created, and the same
            # bytes still deliver the picture as a document.
            if not refused_representation(error):
                raise
            self._degrade(media, error, to="a document")
            return await self._document(bot_id, chat_id, media, reply_to=reply_to)
        return self._id(sent)

    async def send_sticker(
        self, bot_id: int, chat_id: int, media: OutgoingMedia, *, reply_to: int | None
    ) -> int:
        bot = self._bot(bot_id)
        try:
            sent = await bot.send_sticker(
                chat_id=chat_id,
                sticker=self._file(media),
                reply_to_message_id=reply_to,
            )
        except TelegramBadRequest as error:
            # Telegram takes a sticker only as .WEBP/.TGS/.WEBM and validates the
            # file itself, not just the name. A MAX sticker that fails that bar
            # is still a picture.
            if not refused_representation(error):
                raise
            self._degrade(media, error, to="a photo")
            return await self.send_photo(bot_id, chat_id, media, reply_to=reply_to)

        message_id = self._id(sent)
        if getattr(sent, "sticker", None) is None:
            # `ok: true` and no sticker on it: Telegram did not refuse the file,
            # it filed it as a document — a bare Lottie comes back as
            # `application/x-bad-tgsticker`. **The message exists.** This used to
            # send the picture again as a photo, which put two copies of the same
            # image in the chat; the demoted message is what was created and it
            # is what gets mapped.
            logger.warning(
                "Telegram demoted a sticker to a document; keeping the message it made"
            )
        return message_id

    async def send_video(
        self, bot_id: int, chat_id: int, media: OutgoingMedia, *, reply_to: int | None
    ) -> int:
        bot = self._bot(bot_id)
        try:
            sent = await bot.send_video(
                chat_id=chat_id,
                video=self._file(media),
                caption=media.caption,
                caption_entities=self._entities(media.caption_entities),
                duration=media.duration_seconds,
                width=media.width,
                height=media.height,
                thumbnail=self._cover(media),
                reply_to_message_id=reply_to,
                supports_streaming=True,
            )
        except TelegramBadRequest as error:
            if not refused_representation(error):
                raise
            self._degrade(media, error, to="a document")
            return await self._document(bot_id, chat_id, media, reply_to=reply_to)
        return self._id(sent)

    async def send_video_note(
        self, bot_id: int, chat_id: int, media: OutgoingMedia, *, reply_to: int | None
    ) -> int:
        bot = self._bot(bot_id)
        try:
            sent = await bot.send_video_note(
                chat_id=chat_id,
                video_note=self._file(media),
                thumbnail=self._cover(media),
                duration=media.duration_seconds,
                # Telegram calls the side of the square "length"; MAX circles are
                # square by definition, so either dimension is it.
                length=media.width or media.height,
                reply_to_message_id=reply_to,
            )
        except TelegramBadRequest as error:
            # A circle Telegram will not accept as a circle is still worth
            # delivering as a video — but only because it answered.
            if not refused_representation(error):
                raise
            self._degrade(media, error, to="a video")
            return await self.send_video(
                bot_id, chat_id, _as_kind(media, AttachmentKind.VIDEO), reply_to=reply_to
            )
        message_id = self._id(sent)
        if media.caption:
            # A video note carries no caption at all, so the text follows it.
            # A different message with different content — not a second copy of
            # this one — and it is a creating call like any other, so a failure
            # travels rather than being swallowed.
            await self.send_text(bot_id, chat_id, media.caption, reply_to=message_id)
        return message_id

    async def send_voice(
        self, bot_id: int, chat_id: int, media: OutgoingMedia, *, reply_to: int | None
    ) -> int:
        bot = self._bot(bot_id)
        try:
            sent = await bot.send_voice(
                chat_id=chat_id,
                voice=self._file(media),
                caption=media.caption,
                caption_entities=self._entities(media.caption_entities),
                duration=media.duration_seconds,
                reply_to_message_id=reply_to,
            )
        except TelegramBadRequest as error:
            if not refused_representation(error):
                raise
            self._degrade(media, error, to="a document")
            return await self._document(bot_id, chat_id, media, reply_to=reply_to)
        return self._id(sent)

    async def send_audio(
        self, bot_id: int, chat_id: int, media: OutgoingMedia, *, reply_to: int | None
    ) -> int:
        bot = self._bot(bot_id)
        try:
            sent = await bot.send_audio(
                chat_id=chat_id,
                audio=self._file(media),
                caption=media.caption,
                caption_entities=self._entities(media.caption_entities),
                duration=media.duration_seconds,
                title=media.title,
                performer=media.performer,
                reply_to_message_id=reply_to,
            )
        except TelegramBadRequest as error:
            if not refused_representation(error):
                raise
            self._degrade(media, error, to="a document")
            return await self._document(bot_id, chat_id, media, reply_to=reply_to)
        return self._id(sent)

    async def send_document(
        self, bot_id: int, chat_id: int, media: OutgoingMedia, *, reply_to: int | None
    ) -> int:
        return await self._document(bot_id, chat_id, media, reply_to=reply_to)

    async def _document(
        self, bot_id: int, chat_id: int, media: OutgoingMedia, *, reply_to: int | None
    ) -> int:
        """The last representation. Nothing falls back out of here.

        Every degraded path ends at a document, and a document that Telegram
        refuses is the end of the line: a third creating call would be one more
        chance to duplicate and no more chance to deliver.
        """
        bot = self._bot(bot_id)
        sent = await bot.send_document(
            chat_id=chat_id,
            document=self._file(media),
            caption=media.caption,
            caption_entities=self._entities(media.caption_entities),
            reply_to_message_id=reply_to,
        )
        return self._id(sent)

    async def send_album(
        self, bot_id: int, chat_id: int, items: list[OutgoingMedia], *, reply_to: int | None
    ) -> AlbumReceipt:
        bot = self._bot(bot_id)

        group: list[Any] = []
        for item in items:
            file = self._file(item)
            if item.kind is AttachmentKind.PHOTO:
                group.append(
                    InputMediaPhoto(
                        media=file,
                        caption=item.caption,
                        caption_entities=self._entities(item.caption_entities),
                    )
                )
            else:
                group.append(
                    InputMediaVideo(
                        media=file,
                        caption=item.caption,
                        caption_entities=self._entities(item.caption_entities),
                        duration=item.duration_seconds,
                        width=item.width,
                        height=item.height,
                        thumbnail=self._cover(item),
                    )
                )

        try:
            sent = await bot.send_media_group(
                chat_id=chat_id, media=group, reply_to_message_id=reply_to
            )
        except TelegramBadRequest as error:
            # **Product policy, and the whole of it.** Telegram answered that the
            # *group* is not acceptable — mixing kinds it will not mix, or a
            # group it will not build. An answer means no message was created, so
            # sending the parts individually is a first attempt and not a second
            # one, and it delivers a message that would otherwise be lost whole.
            #
            # Any other refusal is permanent and any silence is unconfirmed:
            # neither reaches this branch. That distinction is the difference
            # between this and the `except Exception` that put a second album in
            # a real chat.
            if not refused_group(error):
                raise
            logger.info(
                "Telegram refused the group itself (%s); sending %s item(s) individually",
                error,
                len(items),
            )
            separate = [
                await self._dispatch_single(bot_id, chat_id, item, reply_to=reply_to)
                for item in items
            ]
            check_album_receipt(tuple(separate), expected=len(items))
            return AlbumReceipt(message_ids=tuple(separate))

        # The whole array, in the order Telegram returned it — the only place the
        # id of the second photo ever appears — and checked against the contract
        # the settlement binds by.
        message_ids = tuple(self._id(message) for message in sent or [])
        check_album_receipt(message_ids, expected=len(items))
        group_id = next(
            (
                str(value)
                for message in sent or []
                if (value := getattr(message, "media_group_id", None))
            ),
            None,
        )
        return AlbumReceipt(message_ids=message_ids, media_group_id=group_id)

    async def _dispatch_single(
        self, bot_id: int, chat_id: int, media: OutgoingMedia, *, reply_to: int | None
    ) -> int:
        if media.kind is AttachmentKind.PHOTO:
            return await self.send_photo(bot_id, chat_id, media, reply_to=reply_to)
        return await self.send_video(bot_id, chat_id, media, reply_to=reply_to)

    async def send_text(
        self,
        bot_id: int,
        chat_id: int,
        text: str,
        *,
        reply_to: int | None = None,
        entities: list[dict[str, Any]] | None = None,
        buttons: list[tuple[str, str]] | None = None,
    ) -> int:
        """A notice, a caption tail, a placeholder — all of them real messages.

        This used to answer `None` on any failure, which made every placeholder
        beside a media delivery invisible to the queue: the job was settled on
        the attachments alone while a line of text may or may not have gone out
        beside them. They are creating calls and they are accounted as such.
        """
        bot = self._bot(bot_id)
        sent = await bot.send_message(
            chat_id=chat_id,
            text=text,
            reply_to_message_id=reply_to,
            entities=self._entities(entities),
            reply_markup=_url_keyboard(buttons),
        )
        return self._id(sent)

    async def send_contact(
        self,
        bot_id: int,
        chat_id: int,
        *,
        phone: str,
        first_name: str,
        last_name: str | None = None,
        vcard: str | None = None,
        reply_to: int | None = None,
    ) -> int:
        bot = self._bot(bot_id)
        sent = await bot.send_contact(
            chat_id=chat_id,
            phone_number=phone,
            first_name=first_name,
            last_name=last_name,
            vcard=vcard,
            reply_to_message_id=reply_to,
        )
        return self._id(sent)

    async def send_photo_url(
        self,
        bot_id: int,
        chat_id: int,
        url: str,
        *,
        caption: str,
        reply_to: int | None = None,
        buttons: list[tuple[str, str]] | None = None,
    ) -> int | None:
        """A photo Telegram fetches from a URL — the contact card's avatar.

        The one method here that may answer `None`, and it means one thing:
        Telegram answered that it could not use the URL, so no message exists and
        the caller may draw the card as text instead. A stale avatar is a
        representation problem like any other and is classified as one; a timeout
        fetching it is not, and travels.
        """
        bot = self._bot(bot_id)
        try:
            sent = await bot.send_photo(
                chat_id=chat_id,
                photo=url,
                caption=caption,
                reply_to_message_id=reply_to,
                reply_markup=_url_keyboard(buttons),
            )
        except TelegramBadRequest as error:
            if not refused_representation(error):
                raise
            logger.info("Telegram could not fetch the avatar (%s); the card goes as text", error)
            return None
        return self._id(sent)


def _as_kind(media: OutgoingMedia, kind: AttachmentKind) -> OutgoingMedia:
    from dataclasses import replace

    return replace(media, kind=kind)
